# Generated by Django 4.2.4 on 2023-08-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
