# Generated by Django 4.2.4 on 2023-08-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_items_options_alter_items_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
