# Generated by Django 4.2.4 on 2023-10-07 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_feedbacks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
