# Generated by Django 4.2.4 on 2023-09-03 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationMessage',
            new_name='ConversationMessages',
        ),
        migrations.AlterModelOptions(
            name='conversationmessages',
            options={'verbose_name_plural': 'ConversationMessages'},
        ),
        migrations.AlterModelOptions(
            name='conversations',
            options={'ordering': ('-modified',), 'verbose_name_plural': 'Conversations'},
        ),
    ]
